#!/usr/bin/perl

if ( -d "/etc/vim" ) {
    system( "cp", "/etc/env-tweaks/vimrc", "/etc/vim/vimrc" );
}
else {
    system( "cp", "/etc/env-tweaks/vimrc", "/etc/vimrc" );
}

system( "cp", "/etc/env-tweaks/perltidyrc", "/etc/perltidyrc" );
system( "cp", "/etc/env-tweaks/indent.pro", "/root/.indent.pro" );
