if v:lang =~ "utf8$" || v:lang =~ "UTF-8$"
   set fileencodings=ucs-bom,utf-8,latin1
endif

set nocompatible	" Use Vim defaults (much better!)
set bs=indent,eol,start		" allow backspacing over everything in insert mode
set viminfo='20,\"50	" read/write a .viminfo file, don't store more
			" than 50 lines of registers
set history=50		" keep 50 lines of command line history
set ruler		" show the cursor position all the time

" Only do this part when compiled with support for autocommands
if has("autocmd")
  augroup fedora
  autocmd!
  " In text files, always limit the width of text to 120 characters
  " autocmd BufRead *.txt set tw=120
  " When editing a file, always jump to the last cursor position
  autocmd BufReadPost *
  \ if line("'\"") > 0 && line ("'\"") <= line("$") |
  \   exe "normal! g'\"" |
  \ endif
  " don't write swapfile on most commonly used directories for NFS mounts or USB sticks
  autocmd BufNewFile,BufReadPre /media/*,/mnt/* set directory=~/tmp,/var/tmp,/tmp
  augroup END
endif

if has("cscope") && filereadable("/usr/bin/cscope")
   set csprg=/usr/bin/cscope
   set csto=0
   set cst
   set nocsverb
   " add any database in current directory
   if filereadable("cscope.out")
      cs add cscope.out
   " else add database pointed to by environment
   elseif $CSCOPE_DB != ""
      cs add $CSCOPE_DB
   endif
   set csverb
endif

" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
if &t_Co > 2 || has("gui_running")
  syntax on
  set hlsearch
endif

filetype plugin on

if &term=="xterm"
     set t_Co=8
     set t_Sb=[4%dm
     set t_Sf=[3%dm
endif

" Don't wake up system with blinking cursor:
" http://www.linuxpowertop.org/known.php
let &guicursor = &guicursor . ",a:blinkon0"


"
" Locally added
"
set background=dark

set nocompatible    " Use Vim defaults (much better!)

set showcmd " display incomplete commands
set incsearch " incremental searching
set showmatch

set textwidth=120
"Wrap at this column

set backspace=indent,eol,start
"Make backspaces delete sensibly

set tabstop=4
"Indentation levels every four columns

set shiftwidth=4
"Indent/outdent by four columns

set shiftround
"Indent/outdent to nearest tabstop

set matchpairs+=<:>
"Allow % to bounce between angles too

set ignorecase
set smartcase " if pattern contains uppercase, override

set nobackup

" disable any bells or visual indication
set novisualbell
set noerrorbells
set vb t_vb=
			
" set binary noeol

" expand tabs into spaces for these file types
autocmd BufNewFile,BufRead *.java setlocal expandtab
autocmd BufNewFile,BufRead *.c setlocal expandtab
autocmd BufNewFile,BufRead *.cc setlocal expandtab
autocmd BufNewFile,BufRead *.cpp setlocal expandtab
autocmd BufNewFile,BufRead *.h setlocal expandtab
autocmd BufNewFile,BufRead *.hh setlocal expandtab
autocmd BufNewFile,BufRead *.hpp setlocal expandtab
autocmd BufNewFile,BufRead *.xml setlocal expandtab
autocmd BufNewFile,BufRead *.sql setlocal expandtab
autocmd BufNewFile,BufRead *.pl setlocal expandtab
autocmd BufNewFile,BufRead *.pm setlocal expandtab
autocmd BufNewFile,BufRead *.php setlocal expandtab

" set a reasonable search color
highlight search guibg=LightBlue
highlight search ctermbg=LightBlue

filetype indent off
set noautoindent
set nocindent
set nosmartindent
set indentexpr=

" disable annoying auto commenting
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

" consider replacing this with an all-in-one script that handles perl, c, python
" and calls perltidy/indent/autopep8
map <F2> :%!perltidy<C-M>

set modeline
